### ISSUE TITLE
snyk-delta examples missing

### ISSUE THREAD

**Issue by unitysipu** [snyk-tech-services/snyk-prevent-gh-commit-status#2]
the instructions reference snyk-delta, but the readme doesn't actually have any examples of how to use this with snyk-delta. I'm looking to use this tool in a jenkins pipeline to get some results into github checks for teams that are forced to use the CLI instead of SCM imports.

**Comment by aarlaud** [comment]
Ack. Will update README

**Comment by aarlaud** [comment]
Maybe there was a bit of confusion here. snyk-delta is what does the delta in this snyk-prevent-gh-commit-status, so you don't need to use it with it, it's already in it as a dependency, so you don't need to worry about it.

**Comment by unitysipu** [comment]
yeah maybe it's good to update the documentation that it uses snyk-delta internally
