### ISSUE TITLE
snyk-prevent returns a green status when snyk cli --fail-on upgradable returns 1, the PR doesn't contain package changes

### ISSUE THREAD

**Issue by unitysipu** [snyk-tech-services/snyk-prevent-gh-commit-status#64]
We've hit an issue where in the CLI --fail-on "upgradable" returned 1 because there was a fix to the upstream package, but the snyk-prevent reported green because the client and server diff had no changes. CLI and Server had the same issue on them (the user didn't commit a library change). 

So PR status on github is green, but the Jenkins build has failed because --fail-on "upgradable" exits with 1
This is confusing to the user as you would expect the github check to fail in this scenario.

**Comment by lili2311** [comment]
Support has now been released for this, please try again with the latest version
